spring:
  application:
    name: serveur de ressource
  profiles:
    active: test
  jpa:
      database: POSTGRESQL
      show-sql: true  
  datasource:   
     url: jdbc:postgresql://localhost/comptes 
     username: postgres
     password: postgres
     driverClassName: org.postgresql.Driver
server:
  port: 8000